system('wget -O dates.json "https://www.vizgr.org/historical-events/search.php?format=json&begin_date=00000101&end_date=20230219&lang=en"')
system('cat dates.json')
library(jsonlite)
library(tidyverse)
mylist <- fromJSON('dates.json')
curl -o dates.json "https://www.vizgr.org/historical-events/search.php?format=json&begin_date=00000101&end_date=20230219&lang=en"
mylist <- fromJSON('dates.json')
mydf <- bind_rows(mylist$result[-1])
class(mydf)
class(mydf$date)
head(mydf, 10)
